#!/usr/bin/env bash

set -e

tool_source="${BASH_SOURCE[0]}"
while [ -h "$tool_source" ] ; do tool_source="$(readlink "$tool_source")"; done
sdlc_dir="$( cd -P "$( dirname "$tool_source" )" && pwd )"
prj_home="$( cd -P "$( dirname "$sdlc_dir" )" && pwd )"

cd "${prj_home}"

hash mvn 2>/dev/null || {
  echo 'No Maven executable: aborting'
  exit 1
}

archetype_version=$(mvn org.apache.maven.plugins:maven-help-plugin:3.5.1:evaluate -Dexpression=project.version -q -DforceStdout)

echo "Build archetype version ${archetype_version}"

mvn clean install

mkdir -p target/generate

cd target/generate

mvn archetype:generate -B \
    -DarchetypeGroupId=com.github.enr.archetypes \
    -DarchetypeArtifactId=library-maven-archetype \
    "-DarchetypeVersion=${archetype_version}" \
    -DgroupId=com.example \
    -DartifactId=mylibrary \
    -Dpackage=com.example.library \
    -Dversion=0.0.0

cd mylibrary

mvn install

echo -n "--- fmt " && pwd
/bin/bash .sdlc/fmt

echo -n "--- ci " && pwd
/bin/bash .sdlc/ci

echo -n "--- available dependencies " && pwd
/bin/bash .sdlc/available-updates

git init .
git add .
git commit -a -m "Initial commit"

echo -n "--- update dependencies " && pwd
/bin/bash .sdlc/update-deps

echo -n "--- dependencies diff " && pwd
git --no-pager diff
